name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create serviceAccount.json
        env:
          GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
        run: |
          touch serviceAccount.json
          echo $GCP_SERVICE_ACCOUNT_KEY_FILE >> serviceAccount.json

      - name: Create cypress.env.json
        env:
          CYPRESS_ENV_JSON: ${{ secrets.CYPRESS_ENV_JSON }}
        run: |
          touch cypress.env.json
          echo $CYPRESS_ENV_JSON >> cypress.env.json

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start:ci
          browser: chrome
          wait-on: 'http://localhost:3000'
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
          REACT_APP_DOC_URL: ${{ secrets.REACT_APP_DOC_URL }}
          REACT_APP_GITHUB_URL: ${{ secrets.REACT_APP_GITHUB_URL }}
          REACT_APP_COOKIES_POLICY: ${{ secrets.REACT_APP_COOKIES_POLICY }}
          REACT_APP_GOOGLE_SITE_VERIFICATION: ${{ secrets.REACT_APP_GOOGLE_SITE_VERIFICATION }}
          REACT_APP_FUNCTIONS_URL: ${{ secrets.REACT_APP_FUNCTIONS_URL }}
